package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/NON_EXISTENT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-i586-cygwin/jdk8u51/3951/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Monday, June 8, 2015 6:01:17 PM PDT
*/

public interface NON_EXISTENT
{

  /** Object adapter state indicating that the adapter has been destroyed.
   */
  public static final short value = (short)(4);
}
